

title-Prefix: "JoshuaMC: "

collections:
  authors:
    output: true


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Joshua Mckenna"
      permalink: /blog/:title
      header: false
  - scope:
      path: ""
    values:
      layout: "default"

markdown_ext: "markdown,mkdown,mkdn,mkd,md,markdown.liquid,mkdown.liquid,mkdn.liquid,mkd.liquid,md.liquid"
